# -*- coding: utf-8 -*-
"""Data-Exploration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fAbEM6DayxwRVQJwH77_4S9TViXEjbPz

# Imports
"""

import os
from pathlib import Path
import pandas as pd

# Commented out IPython magic to ensure Python compatibility.
# %ls

"""# Data Exploration"""

from google.colab import drive
drive.mount('/content/drive')

ls data/song_data/A/A/A/

PATH = Path('data/')

len(list((PATH / 'song_data').rglob('*.json')))

"""We have 71 songs metadata."""

len(list((PATH / 'log_data').rglob('*.json')))

"""We have 30 files where each one has logs data."""

len(list(PATH.rglob('*.json')))

"""## Songs Metadata"""

songs_files = list((PATH / 'song_data').rglob('*.json'))
song_df = pd.read_json(songs_files[0], lines=True)
song_df.head()

for i, f in enumerate(songs_files):
    if i == 0:
        songs_df = pd.read_json(f, lines=True)
    else:
        songs_df = songs_df.append(pd.read_json(f, lines=True), ignore_index=True)

songs_df.head()

songs_df.shape

"""## Logs Data"""

logs_files = list((PATH / 'log_data').rglob('*.json'))
log_df = pd.read_json(logs_files[0], lines=True)
log_df.head()

log_df.shape, song_df.shape

logs_files = list((PATH / 'log_data').rglob('*.json'))
for i, f in enumerate(logs_files):
    if i == 0:
        logs_df = pd.read_json(f, lines=True)
    else:
        logs_df = logs_df.append(pd.read_json(f, lines=True), ignore_index=True)

logs_df.head()

logs_df.shape

logs_df.columns

(logs_df['page'] == 'NextSong').sum()

logs_df['page'].value_counts()

logs_files[0].resolve()

